 version: '2'
 services:
   apidoc:
     build: .
     volumes:
       - .:/usr/src/app
     ports:
       - "4567:4567"

     command: /bin/bash -c "echo ==================== B U I L D ====================;
                            pwd;
                            bundle exec middleman build --clean;
                            chmod 777 -R build build/* Gemfile.lock;
                            echo =================== S E R V E R ===================;
                            bundle exec middleman server"
