apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "api-docs.name" . }}
    chart: {{ template "api-docs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "api-docs.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "api-docs.name" . }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
          protocol: {{ .Values.ports.protocol }}
        {{- if .Values.resources }}
        resources: {{ .Values.resources }}
        {{- end }}
        terminationMessagePath: {{ .Values.terminationMessagePath }}
        terminationMessagePolicy: {{ .Values.terminationMessagePolicy}}
      dnsPolicy: {{ .Values.dnsPolicy }}
      nodeSelector:
        role: {{ .Values.nodeSelector.role }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- if .Values.securityContext }}
      securityContext: {}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
