apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ include "api-docs.name" . }}
    chart: {{ include "api-docs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "api-docs.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "apidocs.name" . }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "api-docs.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
