apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-docs.fullname" . }}
  labels:
    app: {{ include "api-docs.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "api-docs.name" . }}
