apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "api-docs.name" . }}
  name: {{ template "api-docs.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.labels.app }}
  sessionAffinity: None
  type: {{ .Values.service.type }}