replicaCount: 2

image:
  repository: harbor.eencloud.com/vms/apidocs
  tag: "{{ .Chart.AppVersion }}"
  imagePullPolicy: Always
 
service:
  type: ClusterIP
  port: 80

nodeSelector:
 role: server

ingress:
  enabled: false
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - apidocs.dev.eagleeyenetworks.com
  tls:
    secretName:
    hosts:
      - apidocs.dev.eagleeyenetworks.com
